#!/usr/bin/env python3
"""
Generate a comprehensive HTML report for a Physlr run.

Combines physical map metrics, assembly metrics (before/after scaffolding),
and backbone visualization into a single HTML report.

Usage: python3 generate_report.py <report.json> <backbone.svg> -o <report.html>
"""

import argparse
import json
import os
import sys


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Physlr Report</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         max-width: 1000px; margin: 40px auto; padding: 0 20px; color: #333;
         line-height: 1.6; }}
  h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
  h2 {{ color: #2c3e50; margin-top: 30px; }}
  table {{ border-collapse: collapse; width: 100%; margin: 15px 0; }}
  th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: right; }}
  th {{ background-color: #3498db; color: white; text-align: left; }}
  tr:nth-child(even) {{ background-color: #f2f2f2; }}
  .improved {{ color: #27ae60; font-weight: bold; }}
  .degraded {{ color: #e74c3c; }}
  .metric-label {{ text-align: left; font-weight: 500; }}
  .summary {{ background: #ecf0f1; padding: 15px; border-radius: 5px; margin: 15px 0; }}
  .svg-container {{ text-align: center; margin: 20px 0; overflow-x: auto; }}
  svg {{ max-width: 100%; height: auto; }}
  footer {{ margin-top: 40px; padding-top: 10px; border-top: 1px solid #ddd;
            color: #999; font-size: 12px; }}
</style>
</head>
<body>
<h1>Physlr Report</h1>

<div class="summary">
<strong>Pipeline:</strong> Physlr v2.0.0 — Next-generation physical maps from linked reads
</div>

<h2>Physical Map</h2>
{physical_map_table}

<h2>Physical Map Visualization</h2>
<div class="svg-container">
{svg_content}
</div>

<h2>Assembly Metrics</h2>
{assembly_table}

<footer>
Generated by Physlr v2.0.0
</footer>
</body>
</html>
"""


def format_number(val):
    """Format a number with commas."""
    try:
        n = int(val)
        return f"{n:,}"
    except (ValueError, TypeError):
        try:
            f = float(val)
            return f"{f:,.1f}"
        except (ValueError, TypeError):
            return str(val)


def make_physical_map_table(pm):
    """Generate HTML table for physical map metrics."""
    rows = []
    for key, val in pm.items():
        rows.append(f'<tr><td class="metric-label">{key}</td>'
                     f'<td>{format_number(val)}</td></tr>')
    return ('<table><tr><th>Metric</th><th>Value</th></tr>'
            + '\n'.join(rows) + '</table>')


def make_assembly_table(before, after):
    """Generate HTML table comparing before/after assembly metrics."""
    if not before and not after:
        return "<p>No assembly metrics available.</p>"

    all_keys = list(dict.fromkeys(
        list(before.keys() if before else []) +
        list(after.keys() if after else [])
    ))

    header = '<tr><th>Metric</th>'
    if before:
        header += '<th>Before Scaffolding</th>'
    if after:
        header += '<th>After Scaffolding</th>'
    if before and after:
        header += '<th>Change</th>'
    header += '</tr>'

    rows = []
    for key in all_keys:
        row = f'<tr><td class="metric-label">{key}</td>'
        b_val = before.get(key, '') if before else ''
        a_val = after.get(key, '') if after else ''

        if before:
            row += f'<td>{format_number(b_val)}</td>'
        if after:
            row += f'<td>{format_number(a_val)}</td>'

        if before and after and b_val and a_val:
            try:
                b_num = float(b_val)
                a_num = float(a_val)
                if b_num > 0:
                    pct = ((a_num - b_num) / b_num) * 100
                    css = 'improved' if pct > 0 else ('degraded' if pct < 0 else '')
                    row += f'<td class="{css}">{pct:+.1f}%</td>'
                else:
                    row += '<td>—</td>'
            except (ValueError, TypeError):
                row += '<td>—</td>'
        elif before and after:
            row += '<td>—</td>'

        row += '</tr>'
        rows.append(row)

    return '<table>' + header + '\n'.join(rows) + '</table>'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("report_json", help="Physlr report JSON file")
    parser.add_argument("-s", "--svg", help="Backbone SVG file")
    parser.add_argument("-o", "--output", required=True, help="Output HTML file")
    args = parser.parse_args()

    with open(args.report_json) as f:
        report = json.load(f)

    pm = report.get("physical_map", {})
    before = report.get("assembly_before", {})
    after = report.get("assembly_after", {})

    svg_content = ""
    if args.svg and os.path.exists(args.svg):
        with open(args.svg) as f:
            svg_content = f.read()
            # Strip XML declaration if present
            if svg_content.startswith("<?xml"):
                svg_content = svg_content[svg_content.index("?>") + 2:].strip()

    html = HTML_TEMPLATE.format(
        physical_map_table=make_physical_map_table(pm),
        assembly_table=make_assembly_table(before, after),
        svg_content=svg_content if svg_content else "<p>No visualization available.</p>",
    )

    with open(args.output, "w") as f:
        f.write(html)

    print(f"Report written to {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
